[package]
name = "identify"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
eyre = "0.6.12"
