[licenses]
allow = ["BSD-3-Clause", "MIT", "Unicode-3.0", "Apache-2.0"]
private = { ignore = true }

[[licenses.exceptions]]
allow = ["Zlib"]
name = "foldhash"
version = "0.1.5"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = [
  # hashlink@0.10.0
  { name = "hashbrown", version = "0.15.5" },
  # socket2@0.6.2
  { name = "windows-sys", version = "0.60.2" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
