[package]
name = "identify-macros"
description = "This crate contains macroses used in Identify"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
uuid = { workspace = true }
