name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'

  check:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./backend

      - name: Check
        working-directory: ./backend
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Formatting
        working-directory: ./backend
        run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest
    needs: [changes, check]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@1.92.0

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./backend

      - name: Test
        working-directory: ./backend
        run: cargo test --verbose --workspace

  detect-unused-dependencies:
    runs-on: ubuntu-latest
    needs: [changes, check]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Machete
        uses: bnjbvr/cargo-machete@main
        with:
          args: ./backend

  detect-unwanted-deps:
    runs-on: ubuntu-latest
    needs: [changes, check]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - uses: actions/checkout@v6

      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: ./backend/Cargo.toml
          command: check
          arguments: --workspace --all-features
